"""initial schema

Revision ID: 238f01f77ac1
Revises:
Create Date: 2026-07-02 17:55:43.219298
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "238f01f77ac1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "demand_partner",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("adapter_module", sa.String(length=120), nullable=False),
        sa.Column("required_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_demand_partner_code"), "demand_partner", ["code"], unique=True)
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("ts_client", sa.BigInteger(), nullable=True),
        sa.Column("ts_server", sa.DateTime(timezone=True), nullable=False),
        sa.Column("account_id", sa.String(length=40), nullable=True),
        sa.Column("placement_id", sa.String(length=40), nullable=True),
        sa.Column("ad_unit_path", sa.String(length=500), nullable=True),
        sa.Column("page_url", sa.Text(), nullable=True),
        sa.Column("session_id", sa.String(length=80), nullable=True),
        sa.Column("engine_version", sa.String(length=40), nullable=True),
        sa.Column("gdpr_applies", sa.Boolean(), nullable=True),
        sa.Column("tc_string", sa.Text(), nullable=True),
        sa.Column("cpm_raw", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("cpm_biased", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("hb_pb", sa.String(length=20), nullable=True),
        sa.Column("bidder", sa.String(length=60), nullable=True),
        sa.Column("props", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ua", sa.Text(), nullable=True),
        sa.Column("ip_country", sa.String(length=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_account_id"), "events", ["account_id"], unique=False)
    op.create_index("ix_events_event_id", "events", ["event_id"], unique=True)
    op.create_index(op.f("ix_events_event_type"), "events", ["event_type"], unique=False)
    op.create_index(op.f("ix_events_placement_id"), "events", ["placement_id"], unique=False)
    op.create_index(
        "ix_events_placement_type_ts",
        "events",
        ["placement_id", "event_type", "ts_server"],
        unique=False,
    )
    op.create_table(
        "publisher",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("account_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("gam_network_code", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_publisher_account_id"), "publisher", ["account_id"], unique=False)
    op.create_table(
        "publisher_demand",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("publisher_id", sa.String(length=40), nullable=False),
        sa.Column("demand_partner_id", sa.String(length=40), nullable=False),
        sa.Column("params_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("floor", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["demand_partner_id"], ["demand_partner.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["publisher_id"], ["publisher.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publisher_id", "demand_partner_id", name="uq_publisher_demand"),
    )
    op.create_index(
        op.f("ix_publisher_demand_demand_partner_id"),
        "publisher_demand",
        ["demand_partner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publisher_demand_publisher_id"), "publisher_demand", ["publisher_id"], unique=False
    )
    op.create_table(
        "site",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("publisher_id", sa.String(length=40), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("app_bundle", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["publisher_id"], ["publisher.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_site_publisher_id"), "site", ["publisher_id"], unique=False)
    op.create_table(
        "ad_unit",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("site_id", sa.String(length=40), nullable=False),
        sa.Column("gam_ad_unit_path", sa.String(length=500), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ad_unit_site_id"), "ad_unit", ["site_id"], unique=False)
    op.create_table(
        "placement",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("ad_unit_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("engine_channel", sa.String(length=40), nullable=False),
        sa.Column("config_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ad_unit_id"], ["ad_unit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_placement_ad_unit_id"), "placement", ["ad_unit_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_placement_ad_unit_id"), table_name="placement")
    op.drop_table("placement")
    op.drop_index(op.f("ix_ad_unit_site_id"), table_name="ad_unit")
    op.drop_table("ad_unit")
    op.drop_index(op.f("ix_site_publisher_id"), table_name="site")
    op.drop_table("site")
    op.drop_index(op.f("ix_publisher_demand_publisher_id"), table_name="publisher_demand")
    op.drop_index(op.f("ix_publisher_demand_demand_partner_id"), table_name="publisher_demand")
    op.drop_table("publisher_demand")
    op.drop_index(op.f("ix_publisher_account_id"), table_name="publisher")
    op.drop_table("publisher")
    op.drop_index("ix_events_placement_type_ts", table_name="events")
    op.drop_index(op.f("ix_events_placement_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index("ix_events_event_id", table_name="events")
    op.drop_index(op.f("ix_events_account_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_demand_partner_code"), table_name="demand_partner")
    op.drop_table("demand_partner")
    op.drop_table("account")
    # ### end Alembic commands ###
