"""Automatic change capture for admin-managed entities.

A ``ContextVar`` carries the acting admin + request/device signals for the current
request (set by ``require_admin``). SQLAlchemy session listeners then turn every
insert/update/delete on an audited table into an :class:`AuditLog` row:

- ``before_flush`` builds rows for updates and deletes — their PKs already exist and
  attribute *history* (old vs new values) is only reliable here.
- ``after_flush`` builds rows for inserts (a new row's autogenerated PK isn't assigned
  until the flush runs) and then writes everything collected for this flush with a
  single core INSERT on the open transaction — so the log commits atomically with the
  change, or not at all. (``before_commit`` fires *before* the flush, so it can't see
  these changes; ``after_flush`` is the correct place.)

Only the tables in ``_AUDITED_TABLES`` are tracked — telemetry ``Event`` rows and
the ``audit_log`` table itself are deliberately excluded (the latter would loop).
Soft deletes (an UPDATE of ``deleted_at``) are recorded as ``delete``/``restore``
rather than ``update``.
"""

from __future__ import annotations

import datetime as dt
from contextvars import ContextVar
from decimal import Decimal
from typing import Any

from sqlalchemy import event, insert, inspect
from sqlalchemy.orm import Session

from app.db import gen_id, utcnow
from app.models import AuditLog

# Request-scoped acting context. Keys: actor, ip, user_agent, method, path, request_id.
_ctx: ContextVar[dict[str, Any] | None] = ContextVar("audit_context", default=None)

# Admin-managed tables we track. Everything else (events, audit_log) is ignored.
_AUDITED_TABLES = frozenset(
    {
        "account",
        "publisher",
        "site",
        "ad_unit",
        "placement",
        "demand_partner",
        "publisher_demand",
    }
)

_PENDING_KEY = "_audit_pending"  # update/delete rows collected in before_flush
_BASE_KEY = "_audit_base"  # per-flush acting context (one timestamp for the flush)


def set_audit_context(
    *,
    actor: str | None,
    ip: str | None,
    user_agent: str | None,
    method: str | None,
    path: str | None,
) -> None:
    """Record who/what is driving the current request. Called by ``require_admin``."""
    _ctx.set(
        {
            "actor": actor,
            "ip": ip,
            "user_agent": user_agent,
            "method": method,
            "path": path,
            "request_id": gen_id("req"),
        }
    )


def _jsonable(value: Any) -> Any:
    """Coerce a column value into something JSONB (json.dumps) accepts."""
    if isinstance(value, dt.datetime):
        return value.isoformat()
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, dict | list | str | int | float | bool) or value is None:
        return value
    return str(value)


def _columns(obj: Any) -> dict[str, Any]:
    """Full JSON-safe snapshot of an instance's mapped columns."""
    mapper = inspect(obj).mapper
    return {c.key: _jsonable(getattr(obj, c.key)) for c in mapper.column_attrs}


def _base_ctx() -> dict[str, Any]:
    ctx = _ctx.get() or {}
    ts = utcnow()
    return {
        "actor": ctx.get("actor"),
        "ip": ctx.get("ip"),
        "user_agent": ctx.get("user_agent"),
        "method": ctx.get("method"),
        "path": ctx.get("path"),
        "request_id": ctx.get("request_id"),
        "created_at": ts,
        "updated_at": ts,
    }


def _row(obj: Any, action: str, base: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": gen_id("aud"),
        "action": action,
        "entity_type": obj.__tablename__,
        "entity_id": getattr(obj, "id", None),
        "before": None,
        "after": None,
        "changed_fields": None,
        **base,
    }


def _diff(obj: Any) -> tuple[dict[str, Any], dict[str, Any], list[str], str]:
    """(before, after, changed_fields, action) for a dirty row, from its history.

    A change to ``deleted_at`` alone flips the action to delete/restore so soft
    deletes read as deletes, not generic updates."""
    state = inspect(obj)
    before: dict[str, Any] = {}
    after: dict[str, Any] = {}
    changed: list[str] = []
    action = "update"
    for attr in state.mapper.column_attrs:
        hist = state.attrs[attr.key].history
        if not hist.has_changes():
            continue
        changed.append(attr.key)
        old = hist.deleted[0] if hist.deleted else None
        new = hist.added[0] if hist.added else None
        before[attr.key] = _jsonable(old)
        after[attr.key] = _jsonable(new)
        if attr.key == "deleted_at":
            if old is None and new is not None:
                action = "delete"
            elif old is not None and new is None:
                action = "restore"
    return before, after, changed, action


@event.listens_for(Session, "before_flush")
def _collect_mutations(session: Session, flush_context: Any, instances: Any) -> None:
    """Updates and deletes — captured here while attribute history is live."""
    base = _base_ctx()
    session.info[_BASE_KEY] = base
    pending: list[dict[str, Any]] = session.info.setdefault(_PENDING_KEY, [])

    for obj in session.deleted:
        if obj.__tablename__ not in _AUDITED_TABLES:
            continue
        row = _row(obj, "delete", base)
        row["before"] = _columns(obj)
        pending.append(row)

    for obj in session.dirty:
        if obj.__tablename__ not in _AUDITED_TABLES:
            continue
        if not session.is_modified(obj, include_collections=False):
            continue
        before, after, changed, action = _diff(obj)
        if not changed:
            continue
        row = _row(obj, action, base)
        row["before"], row["after"], row["changed_fields"] = before, after, changed
        pending.append(row)


@event.listens_for(Session, "after_flush")
def _collect_inserts_and_write(session: Session, flush_context: Any) -> None:
    """Inserts (PKs now assigned) + write the whole batch on the open transaction."""
    base = session.info.get(_BASE_KEY) or _base_ctx()
    pending: list[dict[str, Any]] = session.info.pop(_PENDING_KEY, [])

    for obj in session.new:
        if obj.__tablename__ not in _AUDITED_TABLES:
            continue
        row = _row(obj, "create", base)  # entity_id is now assigned
        row["after"] = _columns(obj)
        pending.append(row)

    session.info.pop(_BASE_KEY, None)
    if pending:
        # autoflush is suppressed mid-flush, so this core INSERT won't recurse.
        session.execute(insert(AuditLog), pending)
